apiVersion: v1
kind: Service
metadata:
  name: {{ include "moo.fullname" . }}-webssh
  labels:
    {{- include "moo.websshLabels" . | nindent 4 }}
spec:
  type: {{ .Values.websshService.type }}
  ports:
    - port: {{ .Values.websshService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "moo.websshSelectorLabels" . | nindent 4 }}
